# Generated by Django 4.2.18 on 2025-01-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar el catálogo de vehículos'), ('add_vehiculomodel', 'Puede agregar los vehículos')]},
        ),
    ]
