# Generated by Django 4.2.18 on 2025-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='f_fabricacion',
            new_name='f_registro',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('SIN ASIGNAR', 'sin_asignar'), ('LACTEOS', 'lacteos'), ('ABARROTES', 'abarrotes'), ('ASEO', 'aseo'), ('FRUTAS', 'frutas'), ('VERDURAS', 'verduras'), ('LICORES', 'licores'), ('BEBIDAS', 'bebidas'), ('MASCOTAS', 'mascotas'), ('LIBRERIA', 'libreria'), ('CONGELADOS', 'congelados')], default='sin_asignar', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
