# Generated by Django 4.1.1 on 2025-01-16 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_directorgeneral_laboratorio_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='f_fabricacion',
            field=models.DateField(default=datetime.date(2015, 1, 1)),
        ),
    ]
