# Generated by Django 4.1.1 on 2025-01-21 17:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_alter_visitas_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='f_fabricacion',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2015, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2025, 1, 21))]),
        ),
    ]
