# Generated by Django 5.1.4 on 2025-01-15 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=150)),
                ('f_ingreso', models.DateField(default=datetime.date.today)),
                ('sueldo', models.DecimalField(decimal_places=2, default='500000', max_digits=12)),
            ],
            options={
                'db_table': 'crudapp_empleado',
            },
        ),
    ]
