# Generated by Django 4.2.18 on 2025-01-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleado',
            table=None,
        ),
    ]
